DROP TABLE USERMASTER
GO

CREATE TABLE [DBO].[CUSTOMERS]
(
	[CUSTOMERID]	[nchar](12) PRIMARY KEY,
	[CUSTOMERNAME]	[nvarchar](50) NOT NULL,
	[CUSTOMERLOGO]	[nvarchar](128) NULL,
	[CUSTOMERTHEME] [nvarchar](12) NOT NULL,
	[CONNECTIONSTRING] [nvarchar](128) NOT NULL,
	[ISADMIN]		[char](1) NOT NULL,	
	[CREATEDBY]		[nvarchar](12) NOT NULL,
	[CREATEDON]		[datetime] DEFAULT GETDATE(),
	[STATUSFLAG]	[char](1) DEFAULT 'N' NOT NULL
) 

INSERT INTO DBO.CUSTOMERS(CUSTOMERID, CUSTOMERNAME,CUSTOMERLOGO,CUSTOMERTHEME,CONNECTIONSTRING,ISADMIN,CREATEDBY) 
	values('ZENSAR','Zensar Technologies','ZENSAR-logo.jpg','Theme1','User ID=sa;Password=Temp1234','Y','admin')
GO
INSERT INTO DBO.CUSTOMERS(CUSTOMERID, CUSTOMERNAME,CUSTOMERLOGO,CUSTOMERTHEME,CONNECTIONSTRING,ISADMIN,CREATEDBY) 
	values('WEBLINK','WebLink Systems','WEBLINK-logo.jpg','Theme1','User ID=sa;Password=Temp1234','Y','admin')
GO

CREATE TABLE [DBO].[USERMASTER]
(
	[USERID]		[nchar](12)  NOT NULL,
	[USERNAME]		[nvarchar](50) NOT NULL,
	[PWD]			[nvarchar](50) NOT NULL,
	[EMAILADDRESS]	[nvarchar](50) NOT NULL,
	[PHONE]			[nvarchar](50) NULL,
	[CUSTOMERID]	[nchar](12)FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMERID),
	[ISADMIN]		[char](1) NOT NULL,
	[CREATEDBY]		[nvarchar](12) NOT NULL,
	[CREATEDON]		[datetime] DEFAULT GETDATE(),
	[STATUSFLAG]	[char](1)DEFAULT 'N' NOT NULL,
	PRIMARY KEY ([CUSTOMERID],[USERID])
)
GO

INSERT INTO DBO.USERMASTER(USERID, USERNAME,PWD,EMAILADDRESS,PHONE,CUSTOMERID,ISADMIN,CREATEDBY) 
	values('admin','Administrator','a','admin@zensar.com','1234567890','WEBLINK','Y','admin')
GO
INSERT INTO DBO.USERMASTER(USERID, USERNAME,PWD,EMAILADDRESS,PHONE,CUSTOMERID,ISADMIN,CREATEDBY) 
	values('admin1','Administrator','a','admin@zensar.com','1234567890','WEBLINK','N','admin')
GO
  INSERT INTO DBO.USERMASTER(USERID, USERNAME,PWD,EMAILADDRESS,PHONE,CUSTOMERID,ISADMIN,CREATEDBY) 
	values('admin','Administrator','a','admin@infogain.com','1234567890','INFOGAIN','Y','admin')
GO
  INSERT INTO DBO.USERMASTER(USERID, USERNAME,PWD,EMAILADDRESS,PHONE,CUSTOMERID,ISADMIN,CREATEDBY) 
	values('abcde','ABCDE','a','abcde@infogain.com','1234567890','INFOGAIN','N','admin')
GO

 CREATE TABLE [dbo].[SUBSCRIPTIONTYPE](
	[SUBSCRIPTIONTYPEID] [nchar](12) PRIMARY KEY,
	[SUBSCRIPTIONTYPENAME] [nvarchar](50) NOT NULL,
	[USERS] [int] DEFAULT 0,
	[STORAGE] [int] DEFAULT 0,
	[BANDWIDTH] [int] DEFAULT 0,
	[TRANSACTIONS1] [int] DEFAULT 0,
	[TRANSACTIONS2] [int] DEFAULT 0,
	[TRANSACTIONS3] [int] DEFAULT 0,
	[DURATION] [nvarchar] (24),
	[CREATEDBY] [nvarchar](12) NOT NULL,
	[CREATEDON] [datetime] DEFAULT GETDATE(),
	[STATUSFLAG] [char](1) DEFAULT 'N'
)
GO

INSERT INTO [SUBSCRIPTIONTYPE] (SUBSCRIPTIONTYPEID, SUBSCRIPTIONTYPENAME, USERS, STORAGE, BANDWIDTH, CREATEDBY, STATUSFLAG)
VALUES 
('Gold-100','Gold 100 Plan',100, 50, 100, 'admin','N')
GO

INSERT INTO [SUBSCRIPTIONTYPE] (SUBSCRIPTIONTYPEID, SUBSCRIPTIONTYPENAME, USERS, STORAGE, BANDWIDTH, DURATION, CREATEDBY, STATUSFLAG)
VALUES 
('Gold-200','Gold 200 Plan',100, 50, 100, 'Annual','admin','N')
GO
